name = "Necro Bot"
uid = "4c5ba0cc-3232-4829-843c-8d2e5c1e2d14"
version = 3
description = "Adds a T3 Necro Bot to each faction. The Necro turns wreckage back into working units through the reclaim process."
author = "Silenthunter, Rockoe10, DigitalCmdr"
url = "https://github.com/TylerJuch/SupComNecroBot"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
icon = "/mods/necro/skull.png"
